/**
 * Ícones do app — exclusivamente Lucide via `react-icons/lu`.
 * Centralizado para padronização e troca fácil. Não importar ícones de outras
 * coleções nem usar emojis na UI.
 */
export {
  LuClipboardList as IconQuotes,
  LuHandshake as IconNegotiations,
  LuUser as IconUser,
  LuUsers as IconUsers,
  LuBell as IconBell,
  LuCalendar as IconAgenda,
  LuCalendarClock as IconScheduled,
  LuClock as IconClock,
  LuMessageSquare as IconChat,
  LuImage as IconImage,
  LuImages as IconImages,
  LuMapPin as IconLocation,
  LuStar as IconStar,
  LuCheck as IconCheck,
  LuCheckCheck as IconConfirmed,
  LuX as IconClose,
  LuChevronRight as IconChevronRight,
  LuChevronLeft as IconChevronLeft,
  LuPlus as IconPlus,
  LuArrowLeft as IconBack,
  LuCreditCard as IconPayment,
  LuFileText as IconProposal,
  LuFileSearch as IconEstimate,
  LuInbox as IconInbox,
  LuSettings as IconSettings,
  LuLogOut as IconLogout,
  LuHistory as IconHistory,
  LuRotateCcw as IconReschedule,
  LuMapPinned as IconArea,
  LuCircleCheck as IconSuccess,
  LuCircleAlert as IconAlert,
  LuCircleDot as IconDot,
  LuPencil as IconEdit,
  LuTrash2 as IconTrash,
  LuWrench as IconExecution,
  LuPartyPopper as IconCelebrate,
  LuHourglass as IconWaiting,
  LuExternalLink as IconExternal,
  LuChartBar as IconCompare,
  LuTriangleAlert as IconWarning,
  LuInfo as IconInfo,
  LuHouse as IconHome,
  LuBriefcase as IconBusiness,
  LuSearch as IconSearch,
  LuShieldCheck as IconShield,
  LuZap as IconFast,
  LuTrendingUp as IconGrowth,
  LuArrowRight as IconArrowRight,
  LuWallet as IconWallet,
  LuChartColumn as IconMetrics,
} from 'react-icons/lu';

export type { IconType } from 'react-icons';
